name: Update Files Action
description: A GitHub action for updating files.
inputs:
  token:
    description: A token for committing the updated files and creating the pull request.
    required: true
  commands:
    description: A comma-separated list of commands to generate the files specified in `paths`.
    required: true
  paths:
    description: A comma-separated list of paths to commit if they were changed.
    required: true
  branch:
    description: A custom branch name.
    required: false
    default: 'update-files'
  delete-branch:
    description: A flag for deleting the branch if it exists.
    required: false
    default: 'false'
  commit.message:
    description: A commit message. It is required if `commit.amend` is `'false'`.
    required: false
  commit.token:
    description: A token that will be used to commit the files instead of token.
    required: false
    default: ''
  commit.amend:
    description: A flag for amending the last commit.
    required: false
    default: 'false'
  pull-request:
    description: A flag for creating a pull request.
    required: false
    default: 'true'
  pull-request.title:
    description: A custom pull request title.
    required: false
  pull-request.body:
    description: A custom pull request body.
    required: false
  pull-request.labels:
    description: A comma-separated list of labels.
    required: false
  pull-request.assignees:
    description: A comma-separated list of assignees.
    required: false
  pull-request.reviewers:
    description: A comma-separated list of reviewers.
    required: false
  pull-request.team-reviewers:
    description: A comma-separated list of team reviewers.
    required: false
  pull-request.milestone:
    description: A milestone number.
    required: false
  pull-request.draft:
    description: A flag to create a pull request draft or a regular pull request.
    required: false
    default: 'false'
outputs:
  commit.sha:
    description: SHA of the new commit
runs:
  using: node12
  main: dist/index.js
branding:
  icon: refresh-cw
  color: red
