name: Label PR

on:
  pull_request:
    types: opened

env:
  LABELS: '{"${{ startsWith(github.head_ref, ''bugfix-'') }}": "bug", "${{ startsWith(github.head_ref, ''deps-'') }}": "dependencies", "${{ startsWith(github.head_ref, ''docs-'') }}": "documentation", "${{ startsWith(github.head_ref, ''feature-'') }}": "feature", "${{ startsWith(github.head_ref, ''refactor-'') }}": "refactor", "${{ startsWith(github.head_ref, ''release-'') }}": "release", "${{ startsWith(github.head_ref, ''repo-'') }}": "repo"}'

jobs:
  label-pr:
    name: Label PR
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.head_ref, 'bugfix-') ||
      startsWith(github.head_ref, 'deps-') ||
      startsWith(github.head_ref, 'docs-') ||
      startsWith(github.head_ref, 'feature-') ||
      startsWith(github.head_ref, 'refactor-') ||
      startsWith(github.head_ref, 'release-') ||
      startsWith(github.head_ref, 'repo-')
    steps:
      - name: Get label id
        id: get-label-id
        uses: octokit/graphql-action@v2.2.20
        with:
          query: |
            query getLabelId($owner: String!, $repo: String!, $label: String!) {
              repository(owner: $owner, name: $repo) {
                label(name: $label) {
                  id
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          label: ${{ fromJSON(env.LABELS)[true] }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add a label
        uses: octokit/graphql-action@v2.2.20
        with:
          query: |
            mutation addLabelsToLabelable($id: ID!, $label: ID!) {
              addLabelsToLabelable(input: {labelableId: $id, labelIds: [$label]}) {
                clientMutationId
              }
            }
          id: ${{ github.event.pull_request.node_id }}
          label: ${{ fromJSON(steps.get-label-id.outputs.data).repository.label.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
