name: Update dist

on:
  push:
    branches: develop
  workflow_dispatch:

jobs:
  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.11.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - name: Update the dist folder
        run: 'npm run build:dist'
      - name: Create a pull request with the updated files
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          paths: 'dist/index.js, dist/index.js.LICENSE.txt'
          branch: build-update-dist
          delete-branch: true
          commit.message: 'BUILD: Update dist'
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of `dist/index.js`.
